# Generated by Django 3.1.1 on 2020-11-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_auto_20201122_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='related_chat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Chat.chat'),
        ),
    ]
