# Generated by Django 3.1.1 on 2020-11-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_auto_20201122_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='related_chat',
        ),
    ]
