# Generated by Django 3.1.1 on 2020-11-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_message_related_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='related_chat',
        ),
    ]
